<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - NegativeLogin Test</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>NegativeLogin Test</h1>
<p>
  Test duration: 6.592s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">testcases.TC003LoginNegativeTest</td>
      </tr>
            
<tr>
  <td class="method">
                  wrongLogin
      </td>
  <td class="duration">
    1.213s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"", ""</span><br />
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [My Account] but found [Account Login]</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:97)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:136)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:575)<br />
              org.testng.Assert.assertEquals(Assert.java:585)<br />
              testcases.TC003LoginNegativeTest.wrongLogin(TC003LoginNegativeTest.java:60)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:498)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)<br />
              org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)<br />
              org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br />
              org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br />
              org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)<br />
              org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.util.ArrayList.forEach(ArrayList.java:1257)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:766)<br />
              org.testng.TestRunner.run(TestRunner.java:587)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:384)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:286)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1109)<br />
              org.testng.TestNG.runSuites(TestNG.java:1039)<br />
              org.testng.TestNG.run(TestNG.java:1007)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  wrongLogin
      </td>
  <td class="duration">
    1.182s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">" ", "test@123"</span><br />
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [My Account] but found [Account Login]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:97)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:136)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:575)<br />
              org.testng.Assert.assertEquals(Assert.java:585)<br />
              testcases.TC003LoginNegativeTest.wrongLogin(TC003LoginNegativeTest.java:60)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:498)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)<br />
              org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)<br />
              org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br />
              org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br />
              org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)<br />
              org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.util.ArrayList.forEach(ArrayList.java:1257)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:766)<br />
              org.testng.TestRunner.run(TestRunner.java:587)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:384)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:286)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1109)<br />
              org.testng.TestNG.runSuites(TestNG.java:1039)<br />
              org.testng.TestNG.run(TestNG.java:1007)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  wrongLogin
      </td>
  <td class="duration">
    1.215s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"s@gmail.com", "test@12"</span><br />
    
        

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [My Account] but found [Account Login]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:97)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:136)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:575)<br />
              org.testng.Assert.assertEquals(Assert.java:585)<br />
              testcases.TC003LoginNegativeTest.wrongLogin(TC003LoginNegativeTest.java:60)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:498)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)<br />
              org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)<br />
              org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br />
              org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br />
              org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)<br />
              org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.util.ArrayList.forEach(ArrayList.java:1257)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:766)<br />
              org.testng.TestRunner.run(TestRunner.java:587)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:384)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:286)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1109)<br />
              org.testng.TestNG.runSuites(TestNG.java:1039)<br />
              org.testng.TestNG.run(TestNG.java:1007)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  wrongLogin
      </td>
  <td class="duration">
    1.719s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"test11@gmail.com", "test@1"</span><br />
    
        

        <a href="javascript:toggleElement('exception-3', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [My Account] but found [Account Login]</b></a><br />
    <div class="stackTrace" id="exception-3">
              org.testng.Assert.fail(Assert.java:97)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:136)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:575)<br />
              org.testng.Assert.assertEquals(Assert.java:585)<br />
              testcases.TC003LoginNegativeTest.wrongLogin(TC003LoginNegativeTest.java:60)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:498)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)<br />
              org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)<br />
              org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br />
              org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br />
              org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)<br />
              org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.util.ArrayList.forEach(ArrayList.java:1257)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:766)<br />
              org.testng.TestRunner.run(TestRunner.java:587)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:384)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:286)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1109)<br />
              org.testng.TestNG.runSuites(TestNG.java:1039)<br />
              org.testng.TestNG.run(TestNG.java:1007)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  wrongLogin
      </td>
  <td class="duration">
    1.263s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"@#@#@gmail.com", "test@123"</span><br />
    
        

        <a href="javascript:toggleElement('exception-4', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [My Account] but found [Account Login]</b></a><br />
    <div class="stackTrace" id="exception-4">
              org.testng.Assert.fail(Assert.java:97)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:136)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:575)<br />
              org.testng.Assert.assertEquals(Assert.java:585)<br />
              testcases.TC003LoginNegativeTest.wrongLogin(TC003LoginNegativeTest.java:60)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
              java.lang.reflect.Method.invoke(Method.java:498)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)<br />
              org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)<br />
              org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br />
              org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br />
              org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)<br />
              org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.util.ArrayList.forEach(ArrayList.java:1257)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:766)<br />
              org.testng.TestRunner.run(TestRunner.java:587)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:384)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:286)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1109)<br />
              org.testng.TestNG.runSuites(TestNG.java:1039)<br />
              org.testng.TestNG.run(TestNG.java:1007)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
